name: LifeStyle
version: ${project.version}
main: net.kunmc.lab.lifestyle.LifeStyle
api-version: 1.15
commands:
  speed-up:
    description: speed-up.
    usage: /<command> [num]
    permission: op
  time:
    description: time.
    usage: /<command> set day,sunset,night,sunrise
    permission: op
